#!/usr/bin/env python3
"""Ingest Markdown from content/ into the Library catalog and static routes."""
from __future__ import annotations
import json, re, shutil, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; CONTENT=ROOT/'content'; OUTPUT=ROOT/'data'/'content_catalog.json'; SHELL=ROOT/'index.html'
REQUIRED={'title','slug','collection','status','summary','themes','relationships'}
ENTITY_TYPES={'articles':'article','notes':'note','project-journals':'project-journal','music-commentary':'music-commentary'}

def scalar(value):
    value=value.strip()
    if not value: return None
    if value.startswith('['):
        try: return json.loads(value)
        except json.JSONDecodeError: return [item.strip().strip('\"\'') for item in value[1:-1].split(',') if item.strip()]
    if value.lower() in {'true','false'}: return value.lower()=='true'
    if re.fullmatch(r'\d+',value): return int(value)
    return value

def parse_document(path):
    source=path.read_text(encoding='utf-8').replace('\r\n','\n')
    if not source.startswith('---\n'): raise ValueError(f'{path.relative_to(ROOT)}: missing front matter')
    _, front, body=source.split('---\n',2)
    metadata={}
    for line in front.splitlines():
        if not line.strip(): continue
        key, sep, value=line.partition(':')
        if not sep: raise ValueError(f'{path.relative_to(ROOT)}: invalid front matter line {line!r}')
        metadata[key.strip()]=scalar(value)
    missing=REQUIRED-metadata.keys()
    if missing: raise ValueError(f'{path.relative_to(ROOT)}: missing {", ".join(sorted(missing))}')
    expected=path.parent.name
    if metadata['collection'] != expected: raise ValueError(f'{path.relative_to(ROOT)}: collection must be {expected}')
    if expected not in ENTITY_TYPES: raise ValueError(f'{path.relative_to(ROOT)}: unsupported collection {expected}')
    entity_type=ENTITY_TYPES[expected]
    metadata.update({
      'id':f'{entity_type}:{metadata["slug"]}', 'type':entity_type,
      'path':f'/library/{expected}/{metadata["slug"]}/',
      'source':path.relative_to(ROOT).as_posix(),
      'body':[p.strip() for p in re.split(r'\n\s*\n',body.strip()) if p.strip()],
      'relationships':[{'type':'related_to','target':target} for target in metadata['relationships']],
    })
    return metadata

def clean_routes():
    for marker in (ROOT/'library').rglob('.generated-content-route'):
        shutil.rmtree(marker.parent)

def ensure_route(record):
    directory=ROOT/record['path'].strip('/'); directory.mkdir(parents=True,exist_ok=True)
    (directory/'index.html').write_text(SHELL.read_text(encoding='utf-8'),encoding='utf-8')
    (directory/'.generated-content-route').write_text('Generated by tools/build_content_catalog.py\n',encoding='utf-8')

def main():
    try:
      clean_routes(); records=[parse_document(p) for p in sorted(CONTENT.rglob('*.md'))]
      ids=[r['id'] for r in records]
      if len(ids)!=len(set(ids)): raise ValueError('duplicate content entity id')
      for record in records: ensure_route(record)
      OUTPUT.write_text(json.dumps({'entries':records},indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
      print(f'Built {OUTPUT.relative_to(ROOT)} with {len(records)} Markdown entries.')
      return 0
    except (ValueError,json.JSONDecodeError) as error:
      print(f'content catalog error: {error}',file=sys.stderr); return 1
if __name__=='__main__': raise SystemExit(main())
