#!/usr/bin/env python3
"""Build the public music catalog from assets/music.

Album metadata comes from each album.json. Track identity and media are derived
only from numbered files such as 01_Used_to_be_easy.wav/.png/.lrc.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import re
import shutil
import subprocess
import sys
import wave
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
MUSIC_ROOT = ROOT / "assets" / "music"
OUTPUT = ROOT / "data" / "music_catalog.json"
SHELL = ROOT / "index.html"
TRACK_PATTERN = re.compile(r"^(?P<number>\d+)[_-](?P<title>.+)\.(?P<extension>wav|png|lrc)$", re.IGNORECASE)
REQUIRED_METADATA = {"title", "year", "status", "cover", "description", "themes", "spotify", "youtube", "soundcloud"}


def slugify(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value or "track"


def display_title(filename_title: str) -> str:
    words = re.sub(r"[_-]+", " ", filename_title).split()
    return " ".join(word if word.isupper() else word.capitalize() for word in words)


def public_path(path: Path) -> str:
    relative = path.relative_to(ROOT).as_posix()
    return "/" + "/".join(quote(part) for part in relative.split("/"))


def wav_duration(path: Path) -> float | None:
    try:
        with contextlib.closing(wave.open(str(path), "rb")) as audio:
            rate = audio.getframerate()
            return audio.getnframes() / rate if rate else None
    except (wave.Error, EOFError):
        pass

    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        return None
    try:
        result = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
            check=True, capture_output=True, text=True,
        )
        return float(result.stdout.strip())
    except (subprocess.CalledProcessError, ValueError):
        return None


def format_duration(seconds: float | None) -> str | None:
    if seconds is None:
        return None
    rounded = round(seconds)
    hours, remainder = divmod(rounded, 3600)
    minutes, secs = divmod(remainder, 60)
    return f"{hours}:{minutes:02d}:{secs:02d}" if hours else f"{minutes}:{secs:02d}"


@dataclass
class TrackFiles:
    number: int
    source_title: str
    files: dict[str, Path] = field(default_factory=dict)


def ensure_route(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "index.html").write_text(SHELL.read_text(encoding="utf-8"), encoding="utf-8")
    (path / ".generated-route").write_text("Generated by tools/build_music_catalog.py\n", encoding="utf-8")


def clean_generated_routes() -> None:
    music_routes = ROOT / "music"
    if not music_routes.exists():
        return
    generated = sorted(music_routes.rglob(".generated-route"), key=lambda item: len(item.parts), reverse=True)
    for marker in generated:
        shutil.rmtree(marker.parent)


def scan_album(directory: Path) -> dict:
    metadata_path = directory / "album.json"
    if not metadata_path.exists():
        raise ValueError(f"{directory.relative_to(ROOT)} is missing album.json")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_METADATA - metadata.keys())
    if missing:
        raise ValueError(f"{metadata_path.relative_to(ROOT)} is missing: {', '.join(missing)}")
    if not isinstance(metadata["themes"], list):
        raise ValueError(f"{metadata_path.relative_to(ROOT)}: themes must be a list")

    grouped: dict[int, TrackFiles] = {}
    for path in sorted(directory.iterdir()):
        match = TRACK_PATTERN.match(path.name)
        if not match:
            continue
        number = int(match.group("number"))
        extension = match.group("extension").lower()
        group = grouped.setdefault(number, TrackFiles(number, match.group("title")))
        if group.source_title.casefold() != match.group("title").casefold():
            raise ValueError(f"Track {number:02d} in {directory.name} has inconsistent names")
        if extension in group.files:
            raise ValueError(f"Track {number:02d} in {directory.name} has duplicate .{extension} files")
        group.files[extension] = path

    album_slug = directory.name
    tracks = []
    for number, group in sorted(grouped.items()):
        title = display_title(group.source_title)
        track_slug = slugify(title)
        duration_seconds = wav_duration(group.files["wav"]) if "wav" in group.files else None
        tracks.append({
            "track": number,
            "slug": track_slug,
            "title": title,
            "path": f"/music/{album_slug}/{track_slug}/",
            "audio": public_path(group.files["wav"]) if "wav" in group.files else None,
            "cover": public_path(group.files["png"]) if "png" in group.files else None,
            "lyrics": public_path(group.files["lrc"]) if "lrc" in group.files else None,
            "duration_seconds": round(duration_seconds, 3) if duration_seconds is not None else None,
            "duration": format_duration(duration_seconds),
        })

    for index, track in enumerate(tracks):
        track["previous"] = ({"title": tracks[index - 1]["title"], "path": tracks[index - 1]["path"]} if index else None)
        track["next"] = ({"title": tracks[index + 1]["title"], "path": tracks[index + 1]["path"]} if index + 1 < len(tracks) else None)
        ensure_route(ROOT / track["path"].strip("/"))

    cover_path = directory / metadata["cover"] if metadata["cover"] else None
    total_seconds = sum(track["duration_seconds"] or 0 for track in tracks)
    has_complete_runtime = bool(tracks) and all(track["duration_seconds"] is not None for track in tracks)
    album = {
        "slug": album_slug,
        "path": f"/music/{album_slug}/",
        **metadata,
        "cover_path": public_path(cover_path) if cover_path and cover_path.exists() else None,
        "track_count": len(tracks),
        "total_runtime_seconds": round(total_seconds, 3) if has_complete_runtime else None,
        "total_runtime": format_duration(total_seconds) if has_complete_runtime else None,
        "tracks": tracks,
    }
    ensure_route(ROOT / "music" / album_slug)
    return album


def build() -> dict:
    clean_generated_routes()
    if not MUSIC_ROOT.exists():
        raise ValueError("assets/music does not exist")
    albums = [scan_album(path) for path in sorted(MUSIC_ROOT.iterdir()) if path.is_dir()]
    catalog = {"generated_from": "assets/music", "albums": albums}
    OUTPUT.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return catalog


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    try:
        catalog = build()
    except (ValueError, json.JSONDecodeError) as error:
        print(f"music catalog error: {error}", file=sys.stderr)
        return 1
    tracks = sum(album["track_count"] for album in catalog["albums"])
    print(f"Built {OUTPUT.relative_to(ROOT)} with {len(catalog['albums'])} albums and {tracks} tracks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
