#!/usr/bin/env python3
"""Build the public music catalog from committed metadata and optional media.

Album metadata and ``tracks.json`` files are committed. FLAC, cover, and LRC
files may be deployed directly to the website and intentionally omitted from
Git. When local FLAC files are available, their STREAMINFO duration is used at
build time; otherwise the browser synchronizes durations from deployed media.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import struct
import sys
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
MUSIC_ROOT = ROOT / "assets" / "music"
OUTPUT = ROOT / "data" / "music_catalog.json"
SHELL = ROOT / "index.html"
TRACK_PATTERN = re.compile(r"^(?P<number>\d+)[_-](?P<title>.+)\.(?P<extension>flac|png|lrc)$", re.IGNORECASE)
REQUIRED_METADATA = {"title", "year", "status", "cover", "description", "themes", "spotify", "youtube", "soundcloud"}
REQUIRED_MEDIA = {"flac", "png", "lrc"}


def slugify(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value or "track"


def display_title(filename_title: str) -> str:
    words = re.sub(r"[_-]+", " ", filename_title).split()
    return " ".join(word if word.isupper() else word.capitalize() for word in words)


def public_path(path: Path) -> str:
    relative = path.relative_to(ROOT).as_posix()
    return "/" + "/".join(quote(part) for part in relative.split("/"))


def flac_duration(path: Path) -> float | None:
    """Read duration from the mandatory FLAC STREAMINFO metadata block."""
    with path.open("rb") as source:
        if source.read(4) != b"fLaC":
            return None
        while True:
            header = source.read(4)
            if len(header) != 4:
                return None
            is_last = bool(header[0] & 0x80)
            block_type = header[0] & 0x7F
            block_size = int.from_bytes(header[1:4], "big")
            payload = source.read(block_size)
            if len(payload) != block_size:
                return None
            if block_type == 0 and block_size >= 18:
                packed = int.from_bytes(payload[10:18], "big")
                sample_rate = packed >> 44
                total_samples = packed & ((1 << 36) - 1)
                return total_samples / sample_rate if sample_rate and total_samples else None
            if is_last:
                return None


def format_duration(seconds: float | None) -> str | None:
    if seconds is None:
        return None
    rounded = round(seconds)
    hours, remainder = divmod(rounded, 3600)
    minutes, secs = divmod(remainder, 60)
    return f"{hours}:{minutes:02d}:{secs:02d}" if hours else f"{minutes}:{secs:02d}"


@dataclass
class TrackFiles:
    number: int
    source_title: str
    files: dict[str, Path] = field(default_factory=dict)


def ensure_route(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "index.html").write_text(SHELL.read_text(encoding="utf-8"), encoding="utf-8")
    (path / ".generated-route").write_text("Generated by tools/build_music_catalog.py\n", encoding="utf-8")


def clean_generated_routes() -> None:
    music_routes = ROOT / "music"
    if not music_routes.exists():
        return
    generated = sorted(music_routes.rglob(".generated-route"), key=lambda item: len(item.parts), reverse=True)
    for marker in generated:
        shutil.rmtree(marker.parent)


def discover_local_tracks(directory: Path) -> dict[int, TrackFiles]:
    grouped: dict[int, TrackFiles] = {}
    for path in sorted(directory.iterdir()):
        match = TRACK_PATTERN.match(path.name)
        if not match:
            continue
        number = int(match.group("number"))
        extension = match.group("extension").lower()
        group = grouped.setdefault(number, TrackFiles(number, match.group("title")))
        if group.source_title.casefold() != match.group("title").casefold():
            raise ValueError(f"Track {number:02d} in {directory.name} has inconsistent names")
        if extension in group.files:
            raise ValueError(f"Track {number:02d} in {directory.name} has duplicate .{extension} files")
        group.files[extension] = path
    return grouped


def load_track_manifest(directory: Path) -> list[TrackFiles] | None:
    manifest_path = directory / "tracks.json"
    if not manifest_path.exists():
        return None
    records = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        raise ValueError(f"{manifest_path.relative_to(ROOT)} must contain a list")
    tracks = []
    for record in records:
        if not isinstance(record, dict) or not {"track", "title", "file"} <= record.keys():
            raise ValueError(f"{manifest_path.relative_to(ROOT)} entries require track, title, and file")
        stem = record["file"]
        if Path(stem).name != stem or Path(stem).suffix:
            raise ValueError(f"{manifest_path.relative_to(ROOT)}: file must be a filename stem")
        tracks.append(TrackFiles(int(record["track"]), str(record["title"]), {
            extension: directory / f"{stem}.{extension}" for extension in REQUIRED_MEDIA
        }))
    numbers = [track.number for track in tracks]
    if numbers != sorted(numbers) or len(numbers) != len(set(numbers)):
        raise ValueError(f"{manifest_path.relative_to(ROOT)} track numbers must be unique and sorted")
    return tracks


def scan_album(directory: Path) -> dict:
    metadata_path = directory / "album.json"
    if not metadata_path.exists():
        raise ValueError(f"{directory.relative_to(ROOT)} is missing album.json")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_METADATA - metadata.keys())
    if missing:
        raise ValueError(f"{metadata_path.relative_to(ROOT)} is missing: {', '.join(missing)}")
    if not isinstance(metadata["themes"], list):
        raise ValueError(f"{metadata_path.relative_to(ROOT)}: themes must be a list")

    manifest_tracks = load_track_manifest(directory)
    local_tracks = discover_local_tracks(directory)
    groups = manifest_tracks if manifest_tracks is not None else list(local_tracks.values())
    album_slug = directory.name
    tracks = []
    for group in groups:
        local_group = local_tracks.get(group.number)
        files = group.files
        if local_group and slugify(local_group.source_title) != slugify(group.source_title):
            raise ValueError(f"Track {group.number:02d} in {directory.name} differs from tracks.json")
        title = group.source_title if manifest_tracks is not None else display_title(group.source_title)
        track_slug = slugify(title)
        audio_path = files["flac"]
        duration_seconds = flac_duration(audio_path) if audio_path.exists() else None
        tracks.append({
            "track": group.number,
            "slug": track_slug,
            "title": title,
            "path": f"/music/{album_slug}/{track_slug}/",
            "audio": public_path(audio_path),
            "cover": public_path(files["png"]),
            "lyrics": public_path(files["lrc"]),
            "duration_seconds": round(duration_seconds, 3) if duration_seconds is not None else None,
            "duration": format_duration(duration_seconds),
            "media_deployed_externally": not audio_path.exists(),
        })

    for index, track in enumerate(tracks):
        track["previous"] = ({"title": tracks[index - 1]["title"], "path": tracks[index - 1]["path"]} if index else None)
        track["next"] = ({"title": tracks[index + 1]["title"], "path": tracks[index + 1]["path"]} if index + 1 < len(tracks) else None)
        ensure_route(ROOT / track["path"].strip("/"))

    cover_path = directory / metadata["cover"]
    known_durations = [track["duration_seconds"] for track in tracks]
    has_complete_runtime = bool(tracks) and all(value is not None for value in known_durations)
    total_seconds = sum(known_durations) if has_complete_runtime else None
    album = {
        "slug": album_slug,
        "path": f"/music/{album_slug}/",
        **metadata,
        "cover_path": public_path(cover_path),
        "track_source": "tracks.json" if manifest_tracks is not None else "local media",
        "track_count": len(tracks),
        "total_runtime_seconds": round(total_seconds, 3) if total_seconds is not None else None,
        "total_runtime": format_duration(total_seconds),
        "tracks": tracks,
    }
    ensure_route(ROOT / "music" / album_slug)
    return album


def build() -> dict:
    clean_generated_routes()
    if not MUSIC_ROOT.exists():
        raise ValueError("assets/music does not exist")
    albums = [scan_album(path) for path in sorted(MUSIC_ROOT.iterdir()) if path.is_dir()]
    catalog = {"generated_from": "assets/music metadata", "albums": albums}
    OUTPUT.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return catalog


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    try:
        catalog = build()
    except (OSError, ValueError, json.JSONDecodeError, struct.error) as error:
        print(f"music catalog error: {error}", file=sys.stderr)
        return 1
    tracks = sum(album["track_count"] for album in catalog["albums"])
    unresolved = sum(track["duration_seconds"] is None for album in catalog["albums"] for track in album["tracks"])
    print(f"Built {OUTPUT.relative_to(ROOT)} with {len(catalog['albums'])} albums and {tracks} tracks ({unresolved} runtimes resolved by deployed media).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
